In [2]:
using ProgressMeter
using JSON

DATASET_DIR = expanduser("~/seungmount/research/Jingpeng/14_zfish/01_data/20190415")

"/home/jingpeng/seungmount/research/Jingpeng/14_zfish/01_data/20190415"

In [10]:
groups = JSON.parsefile("$(DATASET_DIR)/hierarchical_clustering_12.json")

12-element Array{Any,1}:
 Any[82140, 82170, 82173, 82176, 82182, 82183, 82184, 76181, 76568, 76612  …  80733, 80801, 80991, 81174, 81180, 81374, 81425, 81432, 81434, 81775]
 Any[82142, 82194, 76464, 76627, 76750, 76915, 76924, 76926, 76956, 77019  …  81410, 81416, 81521, 81522, 81526, 81563, 81604, 81613, 81785, 81826]
 Any[82143, 82145, 82146, 82192, 82212, 82213, 82267, 76201, 76288, 76541  …  81498, 81569, 81574, 81585, 81631, 81684, 81691, 81755, 81756, 81849]
 Any[82160, 82164, 82197, 76196, 76393, 76403, 76404, 76405, 76452, 76473  …  81497, 81542, 81544, 81582, 81626, 81659, 81671, 81682, 81688, 81758]
 Any[82161, 76184, 76261, 76262, 76263, 76264, 76265, 76266, 76267, 76268  …  81499, 81519, 81553, 81675, 81745, 81748, 81762, 81777, 81783, 81855]
 Any[82169, 76182, 76183, 76185, 76186, 76189, 76190, 76193, 76194, 76195  …  81597, 81650, 81654, 81673, 81686, 81687, 81747, 81757, 81792, 81870]
 Any[82175, 82178, 82180, 82181, 82187, 76457, 76781, 76929, 76952, 77054  …  80716, 80

In [29]:
queryList = [77648, 77710, 77300, 77705, 77305, 77301, 77709, 77672, 77302, 77154, 77646, 77682, 77628, 77295, 77297, 77652, 77292, 77688, 77654, 77658, 77657, 77662, 77296, 77631, 77150, 77618, 77886, 78547, 77158, 78556, 78552, 77665, 77668, 77634, 78553, 77148, 77625, 77641, 77692, 77144, 77643, 77640, 79051, 79066, 78574]

# queryList = [76631]

45-element Array{Int64,1}:
 77648
 77710
 77300
 77705
 77305
 77301
 77709
 77672
 77302
 77154
 77646
 77682
 77628
     ⋮
 77634
 78553
 77148
 77625
 77641
 77692
 77144
 77643
 77640
 79051
 79066
 78574

In [30]:
groupNumList = zeros(Int, length(groups))
for (groupId, group) in enumerate(groups)
    ns = Int[]
    for neuronId in queryList
        if neuronId in group
            push!(ns, neuronId)
            groupNumList[groupId] += 1
        end
    end
    println("group $(groupId) has $(groupNumList[groupId]) motor neurons: $ns")
end


group 1 has 0 motor neurons: Int64[]
group 2 has 0 motor neurons: Int64[]
group 3 has 0 motor neurons: Int64[]
group 4 has 0 motor neurons: Int64[]
group 5 has 0 motor neurons: Int64[]
group 6 has 44 motor neurons: [77648, 77710, 77300, 77705, 77305, 77301, 77709, 77672, 77302, 77154, 77646, 77682, 77628, 77295, 77652, 77292, 77688, 77654, 77658, 77657, 77662, 77296, 77631, 77150, 77618, 77886, 78547, 77158, 78556, 78552, 77665, 77668, 77634, 78553, 77148, 77625, 77641, 77692, 77144, 77643, 77640, 79051, 79066, 78574]
group 7 has 0 motor neurons: Int64[]
group 8 has 0 motor neurons: Int64[]
group 9 has 0 motor neurons: Int64[]
group 10 has 0 motor neurons: Int64[]
group 11 has 0 motor neurons: Int64[]
group 12 has 0 motor neurons: Int64[]
group 13 has 0 motor neurons: Int64[]
group 14 has 0 motor neurons: Int64[]
group 15 has 0 motor neurons: Int64[]
group 16 has 0 motor neurons: Int64[]
group 17 has 0 motor neurons: Int64[]
group 18 has 0 motor neurons: Int64[]
group 19 has 0 motor ne

# Get groups

In [13]:
using JSON
neuronIdList = JSON.parsefile(joinpath(DATASET_DIR, "neuron_ids.json"))["analysis"] |> Vector{Int}

2522-element Array{Int64,1}:
 82140
 82142
 82143
 82145
 82146
 82160
 82161
 82164
 82169
 82170
 82173
 82175
 82176
     ⋮
 81827
 81835
 81839
 81844
 81849
 81851
 81855
 81858
 81868
 81869
 81870
 81874

In [24]:
using HDF5

clusters = h5read("$(DATASET_DIR)/clusters.h5", "clusters") |> Vector{Int};
# make sure that the cluster Id start from 1 rather than 0
if minimum(clusters)==0
    clusters .+= 1
end
@assert minimum(clusters)==1

In [28]:
numGroups = unique(clusters) |> length


groups = Vector{Int}[]
for i in 1:numGroups
    push!(groups, Int[])
end

for (i, neuronId) in enumerate(neuronIdList)
    groupId = clusters[i]
    push!(groups[groupId], neuronId)
end

for (groupId, group) in enumerate(groups)
    println("$(groupId): $(group)\n")
end

1: [76263, 76265, 76266, 76267, 76268, 76272, 76274, 76289, 76290, 76292, 76349, 76350, 76351, 76353, 76354, 76487, 76867, 77497, 77523, 77526, 77533, 77537, 77538, 78391, 78392, 78395, 78397, 78399, 78400, 78401, 78405, 78412, 78419, 78420, 78439, 78440, 79009, 79012, 79013, 79017, 79018, 79023, 80604]

2: [82170, 82173, 82175, 82176, 82178, 82180, 82181, 82182, 82184, 82187, 76187, 76196, 76538, 76544, 76555, 76556, 76561, 76570, 76606, 76610, 76612, 76749, 76750, 76885, 76886, 76887, 76902, 77041, 77047, 77050, 77052, 77060, 77086, 77090, 77108, 77109, 77110, 77112, 77120, 77126, 77138, 77142, 77152, 77233, 77237, 77238, 77239, 77241, 77244, 77248, 77249, 77250, 77253, 77254, 77255, 77259, 77260, 77261, 77262, 77264, 77265, 77298, 77393, 77441, 77442, 77446, 77449, 77450, 77455, 77456, 77457, 77462, 77463, 77465, 77670, 77694, 77695, 77708, 77740, 77889, 77899, 77900, 77934, 77943, 78057, 78058, 78059, 78060, 78083, 78086, 78087, 78088, 78090, 78091, 78092, 78095, 78096, 78097, 7809

10: [77792, 78607, 78608, 78761, 78782, 78783, 78794, 78797, 78838, 78840, 78844, 78846, 79117, 79118, 79119, 79121, 79122, 79130, 79132, 79145, 79146, 79147, 79149, 79153, 79155, 79156, 79178, 79180, 79181, 79182, 79183, 79184, 79188, 79192, 79195, 79222, 79230, 79239, 79248, 79651, 79654, 79682, 79683, 79684, 79685, 79687, 79689, 79690, 79691, 79693, 79694, 79695, 79696, 79698, 79722, 79730, 79734, 79736, 79746, 79751, 79757, 79758, 79760, 79765, 79767, 79768, 79775, 79776, 79778, 79780, 79781, 79782, 79784, 79786, 79787, 79790, 79802, 79803, 79866, 79867, 79881, 79902, 79953, 79957, 80613, 80940, 80949, 81016, 81290, 81302, 81835]

11: [76184, 76192, 76464, 76560, 76903, 76912, 76922, 76923, 76928, 76931, 76933, 76936, 76938, 76941, 76942, 76943, 76944, 76948, 76950, 76955, 76956, 76957, 76964, 76972, 77024, 77025, 77081, 77091, 77092, 77102, 77104, 77885, 77902, 77914, 77930, 77936, 77944, 77945, 77946, 78116, 78120, 78121, 78126, 78128, 78140, 78142, 78151, 78152, 78154, 78172, 78