In [36]:
# Open3D: www.open3d.org                                                          
# The MIT License (MIT)                                                           
# See license file or visit www.open3d.org for details                            
                                                                                  
from open3d import *                                                              
import numpy as np                                                                
import copy                                                                       
                                                                                  
def draw_registration_result(source, target, transformation):                     
    source_temp = copy.deepcopy(source)                                           
    target_temp = copy.deepcopy(target)                                           
    source_temp.paint_uniform_color([1, 0.706, 0])                                
    target_temp.paint_uniform_color([0, 0.651, 0.929])                            
    source_temp.transform(transformation)                                         
    draw_geometries([source_temp, target_temp])                                   
                                                                                  
def align_point_clouds(source_filename, target_filename, threshold=100000):                                                     
    source = read_point_cloud(source_filename)               
    target = read_point_cloud(target_filename)                                                            
#     trans_init = np.asarray(                                                      
#                 [[0.862, 0.011, -0.507,  0.5],                                    
#                 [-0.139, 0.967, -0.215,  0.7],                                    
#                 [0.487, 0.255,  0.835, -1.4],                                     
#                 [0.0, 0.0, 0.0, 1.0]]) 
    trans_init = np.asarray(                                                      
                [[1., 0., 0.,  0.],                                    
                [0., 1., 0.,  0.],                                    
                [0., 0.,  1., 0.],                                     
                [0.0, 0.0, 0.0, 1.0]]) 
#     draw_registration_result(source, target, trans_init)                          
    print("Initial alignment")                                                    
    evaluation = evaluate_registration(source, target,                            
            threshold, trans_init)                                                
    print(evaluation)                                                             
                                                                                  
    print("Apply point-to-point ICP")                                             
    reg_p2p = registration_icp(source, target, threshold, trans_init,             
            TransformationEstimationPointToPoint())                               
    print(reg_p2p)                                                                
    print("Transformation is:")                                                   
    print(reg_p2p.transformation)                                                 
    print("")       
    return reg_p2p.transformation
#     draw_registration_result(source, target, reg_p2p.transformation)              
                                                                                  
#     print("Apply point-to-plane ICP")                                             
#     reg_p2l = registration_icp(source, target, threshold, trans_init,             
#             TransformationEstimationPointToPlane())                               
#     print(reg_p2l)                                                                
#     print("Transformation is:")                                                   
#     print(reg_p2l.transformation)                                                 
#     print("")                                                                     
#     draw_registration_result(source, target, reg_p2l.transformation)              



In [6]:
source_filename = "/opt/Open3D/src/Python/TestData/ICP/cloud_bin_0.pcd"
target_filename = "/opt/Open3D/src/Python/TestData/ICP/cloud_bin_1.pcd"

align_point_clouds(source_filename, target_filename)

Initial alignment
RegistrationResult with fitness = 0.174723, inlier_rmse = 0.011771, and correspondence_set size of 34741
Access transformation to get result.
Apply point-to-point ICP
RegistrationResult with fitness = 0.372450, inlier_rmse = 0.007760, and correspondence_set size of 74056
Access transformation to get result.
Transformation is:
[[ 0.83924644  0.01006041 -0.54390867  0.64639961]
 [-0.15102344  0.96521988 -0.21491604  0.75166079]
 [ 0.52191123  0.2616952   0.81146378 -1.50303533]
 [ 0.          0.          0.          1.        ]]

Apply point-to-plane ICP
RegistrationResult with fitness = 0.620972, inlier_rmse = 0.006581, and correspondence_set size of 123471
Access transformation to get result.
Transformation is:
[[ 0.84023324  0.00618369 -0.54244126  0.64720943]
 [-0.14752342  0.96523919 -0.21724508  0.81018928]
 [ 0.52132423  0.26174429  0.81182576 -1.48366001]
 [ 0.          0.          0.          1.        ]]



In [9]:
import neurom as nm
import os
SWC_DIR = '/usr/people/jingpeng/workspace/zfish_analysis/20_skeletonization/0412/swc'
neuronIds = [77710, 77300]
neuron1 = nm.io.swc.read(os.path.join(SWC_DIR, '{}.swc'.format(neuronIds[0])))
neuron2 = nm.io.swc.read(os.path.join(SWC_DIR, '{}.swc'.format(neuronIds[1])))

In [24]:
import numpy as np
source_filename = '{}.xyz'.format(neuronIds[0])
target_filename = '{}.xyz'.format(neuronIds[1])
np.savetxt(source_filename, neuron1.data_block[:,0:3])
np.savetxt(target_filename, neuron2.data_block[:,0:3])

In [29]:
source = read_point_cloud(source_filename)
np.asarray(source.points)

array([[293920., 124400., 805005.],
       [293920., 124400., 805050.],
       [293920., 124400., 805095.],
       ...,
       [274160., 165600., 792675.],
       [274080., 165600., 792720.],
       [274080., 165600., 792720.]])

In [30]:
target = read_point_cloud(target_filename)
np.asarray(target.points)

array([[287760., 125600., 804555.],
       [287760., 125600., 804510.],
       [287760., 125600., 804465.],
       ...,
       [253360., 163360., 784935.],
       [253280., 163440., 784980.],
       [253280., 163440., 784980.]])

In [40]:
align_point_clouds(source_filename, target_filename, threshold=50000)

Initial alignment
RegistrationResult with fitness = 1.000000, inlier_rmse = 5366.408810, and correspondence_set size of 9753
Access transformation to get result.
Apply point-to-point ICP
RegistrationResult with fitness = 1.000000, inlier_rmse = 4548.567322, and correspondence_set size of 9753
Access transformation to get result.
Transformation is:
[[ 9.99447933e-01  5.49124860e-03 -3.27669966e-02  2.26724272e+04]
 [-2.01682173e-03  9.94455476e-01  1.05139143e-01 -7.89326809e+04]
 [ 3.31626644e-02 -1.05015014e-01  9.93917544e-01  8.02679912e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Apply point-to-plane ICP
RegistrationResult with fitness = 1.000000, inlier_rmse = 5366.408810, and correspondence_set size of 9753
Access transformation to get result.
Transformation is:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

