In [1]:
import os
DATASET_DIR = os.path.expanduser('/usr/people/jingpeng/seungmount/research/Jingpeng/14_zfish/01_data/20190415')

# Hierarchical clustering

In [4]:
import h5py
import numpy as np
with h5py.File(os.path.join(DATASET_DIR, 'data.h5')) as f:
    neuron_id_list = np.asarray(f['neuronIdList'])
    similarity_matrix = np.asarray(f['nblast/zfishTable/meanSimilarityMatrix'])
    clusters = np.asarray(f['nblast/zfishTable/clusters'])
    orders = np.asarray(f['nblast/zfishTable/orders'])
    ordered_clusters = np.asarray(f['nblast/zfishTable/orderedClusters'])
    ordered_neuron_id_list = np.asarray(f['nblast/zfishTable/orderedNeuronIdList'])
    

In [6]:
from scipy.spatial.distance import squareform

from scipy.cluster.hierarchy import dendrogram, linkage, cut_tree
import fastcluster as fc
from matplotlib import pyplot as plt

distance_matrix = - similarity_matrix - np.min(-similarity_matrix)
# transform redundent distance matrix to condensed matrix
y = squareform(distance_matrix)

linked = fc.ward(y)
ct = cut_tree(linked, n_clusters=26).flatten()

dend = dendrogram(linked)

plt.show()

<Figure size 640x480 with 1 Axes>

In [7]:
# from sklearn.cluster import AgglomerativeClustering
# import numpy as np

# agg = AgglomerativeClustering(n_clusters=5, affinity='precomputed', linkage=None)
# ct2 = agg.fit_predict(distance_matrix)
# ct2.labels_

In [9]:
ordered_neuron_ids = neuron_id_list[dend['leaves']]
ordered_group_ids = ct[dend['leaves']]

group_id2neuron_ids = dict()

import pandas as pd
for group_id in pd.unique(ordered_group_ids):
    group_id2neuron_ids[group_id] = []
    
for i,group_id in enumerate(ordered_group_ids):
    neuron_id = ordered_neuron_ids[i]
    group_id2neuron_ids[group_id].append(neuron_id)
    
for group_id,neuron_ids in group_id2neuron_ids.items():
    print('group {}: {}\n'.format(group_id, neuron_ids))
    

group 25: [78757, 78756, 78760, 78759, 78770, 78764, 78765, 76967, 78769, 78775, 81514, 79709, 81511, 78185, 78831, 78627, 79197, 78610, 79173, 79189, 81013, 79142, 79667, 79677, 81024, 78164, 81294, 78606, 79137, 78163, 79864, 78159, 78822, 78179, 78821, 81291, 78178, 79820, 79160, 79135, 79158, 76962, 76966, 79649, 79818, 78166, 78773, 78766, 78768, 78774, 76941, 78888, 76944, 79762, 78834, 78820, 78861, 79162, 79163, 76928, 78177]

group 22: [79118, 78797, 79119, 79902, 79793, 78844, 79121, 76861, 79694, 79049, 79180, 79780, 79752, 78782, 79751, 78607, 79758, 78761, 79182, 79178, 79691, 79787, 79146, 79654, 79188, 79183, 79760, 79690, 79757, 79130, 79698, 79181, 79693, 79145, 79651, 79790, 79689, 79778, 79784, 79122, 79781, 79782, 79120, 79123, 81111, 81762, 80946, 79662, 81812, 81874, 81298, 81517, 78791, 79680, 79759, 79872, 81501, 80610, 79726, 80581, 79728, 79738, 79959, 79719, 79661, 79742, 78168, 79740, 81815, 79672, 81798, 79838, 80937, 78134, 79136, 78155, 78162, 79960, 7916

In [34]:
import scipy.cluster.hierarchy as hc
print('the two cluster is the isomorphic? ', hc.is_isomorphic(ct,clusters))

from sklearn.metrics import adjusted_rand_score

adjusted_rand_score(clusters, ct)

the two cluster is the isomorphic?  False


0.5608918074452931

In [27]:
ct2[:100]

array([ 0,  1,  0,  0,  0,  0,  2,  0,  3,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  0,  0,  0,  0,  5,  1,  6,  7,  7,  8,  9,  7, 10, 11,
        3, 11,  6, 12,  7,  7,  7,  2, 13,  7,  7,  7, 10, 14, 15, 15,  3,
       15, 15, 15, 15, 15,  7,  3, 15, 15, 15, 15, 16,  3,  3,  7,  3,  7,
        3,  9,  3, 15, 15,  3, 15,  7, 11, 11, 11, 17, 11, 11, 11, 13, 11,
       18,  2, 18,  7,  7,  7,  7,  7, 11, 17,  7,  7, 11, 18, 11])

In [53]:
ct[:100]

array([ 0,  1,  0,  0,  0,  0,  2,  0,  3,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  0,  0,  0,  0,  5,  1,  6,  7,  7,  8,  9,  7, 10, 11,
        3, 11,  6, 12,  7,  7,  7,  2, 13,  7,  7,  7, 10, 14, 15, 15,  3,
       15, 15, 15, 15, 15,  7,  3, 15, 15, 15, 15, 16,  3,  3,  7,  3,  7,
        3,  9,  3, 15, 15,  3, 15,  7, 11, 11, 11, 17, 11, 11, 11, 13, 11,
       18,  2, 18,  7,  7,  7,  7,  7, 11, 17,  7,  7, 11, 18, 11])

In [52]:
(clusters - 1)[:100]

array([ 0,  1,  0,  0,  0,  2,  3,  2,  4,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  0,  0,  0,  0,  6,  1,  7,  8,  8,  9, 10,  8, 11, 12,
        4, 12, 13,  1,  8,  8,  8,  3,  4,  8,  8,  8, 13, 14, 15, 15,  4,
       15, 15, 15, 15, 15,  8, 10, 15, 15, 15, 15, 11, 10,  4,  8, 10,  8,
       10, 10,  4, 15, 15,  4, 15,  8,  8,  8,  8,  4, 12,  8, 12, 12, 12,
       12, 16, 12,  8,  8,  8,  8,  8,  8,  8,  8,  8, 12, 12,  8],
      dtype=int32)

In [1]:
import neuroglancer as ng